sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t umeshbhat/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run umeshbhat/react-test npm test -- --coverage

after_success:
  - docker build -t umeshbhat/multi-client ./client
  - docker build -t umeshbhat/multi-nginx ./nginx
  - docker build -t umeshbhat/multi-server ./server
  - docker build -t umeshbhat/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push umeshbhat/multi-client
  - docker push umeshbhat/multi-nginx
  - docker push umeshbhat/multi-server
  - docker push umeshbhat/multi-worker
deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: 'multi-docker'
  env: 'MultiDockerFib'
  bucket_name: 'elasticbeanstalk-us-east-2-664592431862'
  bucket_path: 'multi-docker'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
